name: komu_chatapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_ui_firestore: ^2.0.1
  google_fonts: ^6.3.3
  uuid: ^4.5.2
  package_info_plus: ^9.0.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/O.png
